### ISSUE TITLE
Integrate linked trip to the GTFS data

### ISSUE THREAD

**Issue by kat-ka** [fahrgemeinschaft/ride-to-gtfs-converter#9]
* link needs to be generated
* example link: https://www.fahrgemeinschaft.de/mitfahren/brigachtal/vaihingen/
* this needs to be saved as `route_url` in routes.txt

**Comment by yncyrydybyl** [comment]
I think its more like https://live.ride2go.com/#/trip/223c8a2f-e6f6-6354-75e2-fa24a4aa4695/de ...
https://docs.ride2go.dev/frontend/deeplinks/trip_based.html
